-- Domain constraints for the enum-like TEXT columns.
--
-- GENERATED by scripts/gen-check-constraints.mjs from
-- src/lib/db/column-domains.ts. Do not edit by hand — regenerate.
--
-- Every lifecycle column was bare TEXT with no CHECK, so the state
-- machines were enforced only in application code. Added NOT VALID so the
-- ALTER takes a short lock without scanning; VALIDATE is a separate,
-- deliberate step because it is what surfaces pre-existing bad rows.
--
-- Pre-flight: run scripts/check-domain-violations.sql first. If it
-- returns any row, fix the data before validating.

-- User.role
DO $$
BEGIN
    ALTER TABLE "User"
        ADD CONSTRAINT "User_role_check"
        CHECK ("role" IN ('ADMIN', 'COLLABORATOR', 'CUSTOMER', 'GOOGLER', 'PARTNER')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- Company.kind
DO $$
BEGIN
    ALTER TABLE "Company"
        ADD CONSTRAINT "Company_kind_check"
        CHECK ("kind" IN ('CUSTOMER', 'PARTNER')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- Company.verificationStatus
DO $$
BEGIN
    ALTER TABLE "Company"
        ADD CONSTRAINT "Company_verificationStatus_check"
        CHECK ("verificationStatus" IN ('APPROVED', 'PENDING', 'REJECTED')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- PartnerProfile.tier
DO $$
BEGIN
    ALTER TABLE "PartnerProfile"
        ADD CONSTRAINT "PartnerProfile_tier_check"
        CHECK ("tier" IN ('MEMBER', 'PARTNER', 'PREMIER')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- Lead.status
DO $$
BEGIN
    ALTER TABLE "Lead"
        ADD CONSTRAINT "Lead_status_check"
        CHECK ("status" IN ('BRIEF_STARTED', 'BRIEF_SUBMITTED', 'CLAIMED', 'INVITED', 'LOST', 'MATCHED', 'MEETING_SCHEDULED', 'PROPOSAL_RECEIVED', 'WON')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- ProjectBrief.stage
DO $$
BEGIN
    ALTER TABLE "ProjectBrief"
        ADD CONSTRAINT "ProjectBrief_stage_check"
        CHECK ("stage" IN ('CLOSED', 'INTAKE', 'INTRODUCTION', 'PROPOSALS', 'REVIEW', 'SELECTION', 'SHORTLIST', 'SOURCING')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- ProjectBrief.leadState
DO $$
BEGIN
    ALTER TABLE "ProjectBrief"
        ADD CONSTRAINT "ProjectBrief_leadState_check"
        CHECK ("leadState" IN ('CANCELLED', 'CLARIFICATION_NEEDED', 'COMPANY_SELECTED', 'COMPARISON_RELEASED', 'COMPLETED', 'DRAFT', 'DROPPED_OFF', 'IN_TRIAGE', 'LEAD_APPROVED', 'MEETINGS_SCHEDULED', 'PARTNERS_SELECTED', 'PROPOSALS_IN_REVIEW', 'REVEAL_APPROVED', 'SENT_TO_PARTNERS', 'STALLED', 'SUBMITTED')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- ProjectBrief.status
DO $$
BEGIN
    ALTER TABLE "ProjectBrief"
        ADD CONSTRAINT "ProjectBrief_status_check"
        CHECK ("status" IN ('ACTIVE', 'ARCHIVED', 'DRAFT')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- Match.status
DO $$
BEGIN
    ALTER TABLE "Match"
        ADD CONSTRAINT "Match_status_check"
        CHECK ("status" IN ('DECLINED', 'EXPIRED', 'EXTENSION_REQUESTED', 'INVITED', 'IN_FINAL_THREE', 'NOT_SELECTED', 'PARTNER_ACCEPTED', 'PARTNER_DECLINED', 'PROPOSAL_EXPIRED', 'PROPOSAL_SUBMITTED', 'QC_PASSED', 'REVIEW_APPROVED', 'SELECTED', 'SHORTLISTED', 'SOURCED', 'WITHDRAWN')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- Proposal.status
DO $$
BEGIN
    ALTER TABLE "Proposal"
        ADD CONSTRAINT "Proposal_status_check"
        CHECK ("status" IN ('CLARIFICATION_NEEDED', 'DECLINED', 'DRAFT', 'INTERNALLY_APPROVED', 'INTERNAL_REVIEW', 'IN_QC', 'QC_PASSED', 'SELECTED', 'SHORTLISTED', 'SUBMITTED')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- BriefCollaborator.role
DO $$
BEGIN
    ALTER TABLE "BriefCollaborator"
        ADD CONSTRAINT "BriefCollaborator_role_check"
        CHECK ("role" IN ('EDITOR', 'VIEWER')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- BriefCollaborator.status
DO $$
BEGIN
    ALTER TABLE "BriefCollaborator"
        ADD CONSTRAINT "BriefCollaborator_status_check"
        CHECK ("status" IN ('ACTIVE', 'INVITED', 'REMOVED')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- TimerInstance.timerType
DO $$
BEGIN
    ALTER TABLE "TimerInstance"
        ADD CONSTRAINT "TimerInstance_timerType_check"
        CHECK ("timerType" IN ('company_select', 'lead_accept', 'proposal_submit', 'reveal_to_meeting', 'stagger_release', 'triage')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- TimerInstance.status
DO $$
BEGIN
    ALTER TABLE "TimerInstance"
        ADD CONSTRAINT "TimerInstance_status_check"
        CHECK ("status" IN ('active', 'cancelled', 'expired', 'satisfied')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- Engagement.status
DO $$
BEGIN
    ALTER TABLE "Engagement"
        ADD CONSTRAINT "Engagement_status_check"
        CHECK ("status" IN ('ACTIVE', 'CANCELLED', 'DELIVERED', 'PENDING_ACCEPTANCE')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- EngagementMilestone.status
DO $$
BEGIN
    ALTER TABLE "EngagementMilestone"
        ADD CONSTRAINT "EngagementMilestone_status_check"
        CHECK ("status" IN ('BLOCKED', 'COMPLETED', 'IN_PROGRESS', 'PENDING')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- WorkspaceJoinRequest.status
DO $$
BEGIN
    ALTER TABLE "WorkspaceJoinRequest"
        ADD CONSTRAINT "WorkspaceJoinRequest_status_check"
        CHECK ("status" IN ('APPROVED', 'CANCELLED', 'DECLINED', 'PENDING')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- RiskRadarReport.overall
DO $$
BEGIN
    ALTER TABLE "RiskRadarReport"
        ADD CONSTRAINT "RiskRadarReport_overall_check"
        CHECK ("overall" IN ('block', 'failed', 'info', 'warn')) NOT VALID;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_table  THEN NULL;
    WHEN undefined_column THEN NULL;
END $$;

-- ── Validation ─────────────────────────────────────────────────
-- Separate statements so a failure names the offending table and the
-- rest of the constraints stay in place (NOT VALID still blocks new bad
-- writes, which is the important half).

DO $$
BEGIN
    ALTER TABLE "User" VALIDATE CONSTRAINT "User_role_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "Company" VALIDATE CONSTRAINT "Company_kind_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "Company" VALIDATE CONSTRAINT "Company_verificationStatus_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "PartnerProfile" VALIDATE CONSTRAINT "PartnerProfile_tier_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "Lead" VALIDATE CONSTRAINT "Lead_status_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "ProjectBrief" VALIDATE CONSTRAINT "ProjectBrief_stage_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "ProjectBrief" VALIDATE CONSTRAINT "ProjectBrief_leadState_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "ProjectBrief" VALIDATE CONSTRAINT "ProjectBrief_status_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "Match" VALIDATE CONSTRAINT "Match_status_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "Proposal" VALIDATE CONSTRAINT "Proposal_status_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "BriefCollaborator" VALIDATE CONSTRAINT "BriefCollaborator_role_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "BriefCollaborator" VALIDATE CONSTRAINT "BriefCollaborator_status_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "TimerInstance" VALIDATE CONSTRAINT "TimerInstance_timerType_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "TimerInstance" VALIDATE CONSTRAINT "TimerInstance_status_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "Engagement" VALIDATE CONSTRAINT "Engagement_status_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "EngagementMilestone" VALIDATE CONSTRAINT "EngagementMilestone_status_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "WorkspaceJoinRequest" VALIDATE CONSTRAINT "WorkspaceJoinRequest_status_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "RiskRadarReport" VALIDATE CONSTRAINT "RiskRadarReport_overall_check";
EXCEPTION
    WHEN undefined_table  THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

-- ── Post-condition ─────────────────────────────────────────────
DO $$
DECLARE
    expected text[] := ARRAY[
        'User_role_check',
        'Company_kind_check',
        'Company_verificationStatus_check',
        'PartnerProfile_tier_check',
        'Lead_status_check',
        'ProjectBrief_stage_check',
        'ProjectBrief_leadState_check',
        'ProjectBrief_status_check',
        'Match_status_check',
        'Proposal_status_check',
        'BriefCollaborator_role_check',
        'BriefCollaborator_status_check',
        'TimerInstance_timerType_check',
        'TimerInstance_status_check',
        'Engagement_status_check',
        'EngagementMilestone_status_check',
        'WorkspaceJoinRequest_status_check',
        'RiskRadarReport_overall_check'
    ];
    name    text;
    missing text[] := '{}';
BEGIN
    FOREACH name IN ARRAY expected LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
             WHERE conname = name AND contype = 'c'
        ) THEN
            missing := array_append(missing, name);
        END IF;
    END LOOP;

    IF array_length(missing, 1) > 0 THEN
        RAISE EXCEPTION
            'domain constraints missing (bad table/column name?): %',
            array_to_string(missing, ', ');
    END IF;

    RAISE NOTICE 'all % domain constraints present', array_length(expected, 1);
END $$;
