/**
 * Database domain constraints.
 *
 * Every enum-like column was bare TEXT with no CHECK anywhere in the
 * schema, so the state machines were enforced only in application code —
 * fine for app writes, worthless against a psql session, a backfill
 * script, or a future service.
 *
 * The constraints are generated from `src/lib/db/column-domains.ts`. These
 * tests fail if the generated migration and that source drift apart, and
 * if the domains stop covering the states the state machines can actually
 * produce (the original reason a naive constraint would have rejected
 * live rows: `enums.ts` MATCH_STATUSES had fallen behind INVITE_STATES).
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  COLUMN_DOMAINS,
  checkClause,
  sqlValueList,
} from "@/lib/db/column-domains";
import { LEAD_STATES } from "@/lib/enums";

const read = (p: string) => readFileSync(resolve(process.cwd(), p), "utf8");
const migration = read("db/migrations/20260812_column_domains.sql");
const preflight = read("scripts/check-domain-violations.sql");

describe("generated CHECK constraints", () => {
  it("covers every declared domain", () => {
    for (const d of COLUMN_DOMAINS) {
      expect(migration, `${d.table}.${d.column} missing`).toContain(
        `"${d.constraint}"`,
      );
    }
  });

  it("emits exactly the declared values for each column", () => {
    for (const d of COLUMN_DOMAINS) {
      // The generator sorts values; checkClause does too.
      expect(
        migration,
        `${d.table}.${d.column} value list drifted`,
      ).toContain(`"${d.column}" IN ${sqlValueList(d.values)}`);
      expect(checkClause(d)).toContain(d.column);
    }
  });

  it("adds constraints NOT VALID and validates them separately", () => {
    // NOT VALID keeps the ALTER cheap (no table scan) while still
    // blocking new bad writes; VALIDATE is the part that can fail on
    // legacy rows, so it must be its own step.
    const notValidCount = (migration.match(/NOT VALID;/g) ?? []).length;
    expect(notValidCount).toBe(COLUMN_DOMAINS.length);
    for (const d of COLUMN_DOMAINS) {
      expect(migration).toContain(
        `VALIDATE CONSTRAINT "${d.constraint}"`,
      );
    }
  });

  it("is idempotent — re-running cannot fail on an existing constraint", () => {
    expect(migration).toContain("WHEN duplicate_object THEN NULL;");
  });

  it("documents that it is generated, so nobody hand-edits it", () => {
    expect(migration).toContain("GENERATED by scripts/gen-check-constraints.mjs");
  });

  it("asserts afterwards that every constraint actually landed", () => {
    // The ADD blocks swallow undefined_table/undefined_column so the
    // migration is safe against an older schema — but that also means a
    // typo'd table or column silently produces NO constraint while the
    // migration reports success. This caught a real mistake during
    // rehearsal: `tier` lives on PartnerProfile, not Company.
    expect(migration).toContain("domain constraints missing");
    expect(migration).toContain("RAISE EXCEPTION");
    for (const d of COLUMN_DOMAINS) {
      expect(migration).toContain(`'${d.constraint}'`);
    }
  });

  it("has one ADD and one VALIDATE per domain — no duplicated blocks", () => {
    const adds = (migration.match(/ADD CONSTRAINT/g) ?? []).length;
    const validates = (migration.match(/VALIDATE CONSTRAINT/g) ?? []).length;
    expect(adds).toBe(COLUMN_DOMAINS.length);
    expect(validates).toBe(COLUMN_DOMAINS.length);
  });

  it("targets PartnerProfile.tier, not Company.tier", () => {
    // Verified against a real PG16 database: `tier` exists only on
    // PartnerProfile.
    expect(migration).toContain('"PartnerProfile_tier_check"');
    expect(migration).not.toContain("Company_tier_check");
    expect(preflight).toContain("PartnerProfile.tier");
    expect(preflight).not.toContain("Company.tier");
  });
});

describe("domains match what the code can actually write", () => {
  it("Match.status covers the invite state machine, not just enums.ts", () => {
    const match = COLUMN_DOMAINS.find(
      (d) => d.table === "Match" && d.column === "status",
    )!;
    // These are written by transitionInvite but were absent from
    // enums.ts MATCH_STATUSES — a constraint from that list alone would
    // have rejected live rows.
    for (const state of [
      "QC_PASSED",
      "PROPOSAL_SUBMITTED",
      "PROPOSAL_EXPIRED",
      "NOT_SELECTED",
      "EXTENSION_REQUESTED",
      "EXPIRED",
      "SELECTED",
    ]) {
      expect(match.values, `${state} missing`).toContain(state);
    }
  });

  it("Proposal.status covers the proposal state machine", () => {
    const proposal = COLUMN_DOMAINS.find(
      (d) => d.table === "Proposal" && d.column === "status",
    )!;
    for (const state of [
      "IN_QC",
      "CLARIFICATION_NEEDED",
      "QC_PASSED",
      "INTERNAL_REVIEW",
      "INTERNALLY_APPROVED",
    ]) {
      expect(proposal.values, `${state} missing`).toContain(state);
    }
  });

  it("ProjectBrief.leadState covers every canonical lead state", () => {
    const leadState = COLUMN_DOMAINS.find(
      (d) => d.table === "ProjectBrief" && d.column === "leadState",
    )!;
    for (const state of LEAD_STATES) {
      expect(leadState.values, `${state} missing`).toContain(state);
    }
  });

  it("RiskRadarReport.overall admits the 'failed' sentinel", () => {
    const overall = COLUMN_DOMAINS.find(
      (d) => d.table === "RiskRadarReport" && d.column === "overall",
    )!;
    // Without this the fail-closed submit gate could not record that the
    // model call never completed.
    expect(overall.values).toContain("failed");
  });

  it("TimerInstance covers the admin-side timers added for SLA cover", () => {
    const types = COLUMN_DOMAINS.find(
      (d) => d.table === "TimerInstance" && d.column === "timerType",
    )!;
    expect(types.values).toContain("triage");
    expect(types.values).toContain("reveal_to_meeting");
  });
});

describe("pre-flight violation report", () => {
  it("checks every constrained column before VALIDATE is run", () => {
    // VALIDATE is what fails on legacy rows, so the operator needs a
    // report naming the offending values first.
    for (const d of COLUMN_DOMAINS) {
      // The report covers the columns that exist on long-lived tables.
      if (["EngagementMilestone", "WorkspaceJoinRequest", "Engagement"].includes(d.table)) {
        continue; // new tables, created empty by earlier migrations
      }
      expect(preflight, `${d.table}.${d.column} not pre-flighted`).toContain(
        `${d.table}.${d.column}`,
      );
    }
  });
});

describe("timestamptz migration", () => {
  const forward = read("db/migrations/20260812_timestamptz.sql");
  const rollback = read(
    "db/migrations/rollback/20260812_timestamptz_down.sql",
  );

  it("sets the session timezone to UTC to avoid a full table rewrite", () => {
    // On PG12+ this is what makes the conversion metadata-only. Without
    // it, 219 columns across 72 tables get rewritten under lock.
    expect(forward).toContain("SET LOCAL TimeZone = 'UTC'");
    expect(forward).toContain("AT TIME ZONE ''UTC''");
  });

  it("bounds the locks so a blocked ALTER fails instead of stalling reads", () => {
    expect(forward).toContain("SET LOCAL lock_timeout");
    expect(forward).toContain("SET LOCAL statement_timeout");
  });

  it("drives off the live catalog rather than a hardcoded column list", () => {
    expect(forward).toContain("information_schema.columns");
    expect(forward).toContain("'timestamp without time zone'");
  });

  it("ships a rollback that preserves _migration.appliedAt", () => {
    expect(rollback).toContain("timestamp(3)");
    // That column was already timestamptz before this change.
    expect(rollback).toContain('"_migration"');
    expect(rollback).toContain("appliedAt");
  });
});
